import { Geist, Geist_Mono } from "next/font/google";
import "@/app/styles/globals.css";
import Header from "../component/header";
import { ThemeProvider } from "../component/changeTheme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create Saeed Choupani",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden @container`}
        >
          <Header />
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
